version: '3'

services: 
  app: # サービス名
    build: . # ①ビルドに使うDockerfileの場所
    tty: true # ②コンテナの永続化
    volumes:
        - ./app:/go/src/app
    ports:
      - 80:${PORT}
    # env_file:
    #   - .env
    environment:
      - PORT=${PORT}
      - GO111MODULE=${GO111MODULE}
      - GO_ENV=${GO_ENV}
  neo4j:
    image: neo4j
    restart: always
    ports: 
      - 57474:7474
      - 57687:7687
    volumes: 
      - ./volumes/neo4j/data:/data
      - ./import:/var/lib/neo4j/import
