version: '3'

services: 
  app: # サービス名
    build: . # ①ビルドに使うDockerfileの場所
    tty: true # ②コンテナの永続化
    volumes:
        - ./app:/go/src/app # ③マウントディレクトリ
    ports: 
      - 8080:8080
    # env_file: 
    #   - .env
    environment: 
      - NEO4J_DATABASE:neo4j
      - NEO4J_VERSION:4
      - NEO4J_URL:bolt://neo4j:7687
      - NEO4J_USER:test
      - NEO4J_PASSWORD:example
  neo4j:
    image: neo4j
    restart: always
    ports: 
      - 57474:7474
      - 57687:7687
    volumes: 
      - ./volumes/neo4j/data:/data
